version: '3.1'

services:
  db_artise:
    image: mysql
    ports:
      - 5123:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - my_db:/var/lib/mysql

  adminer:
    image: phpmyadmin
    links:
      - db_artise
    environment:
      PMA_HOST: db_artise
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 7000:80

volumes:
    my_db: